a = input('digite algo')
print('o tipo primitivo desse valor é :', type(a))
print('so tem espacos ?', a.isspace())
print('é um numero', a.isnumeric())
print('é alfabetico', a.isalpha())
print('é alfanumerico', a.isalnum())
print('esta em maiusculas', a.isupper())
